name: Butler Push
on:
  push:
    branches: [ master ]
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: king-fortress
          ITCH_USER: tagurit
          PACKAGE: /
